import os
import re
from pathlib import Path

class HermesTunnelService:
    def __init__(self, log_file_path: str = "/shared/tunnel.log"):
        self.log_file_path = Path(log_file_path)

    def get_active_tunnel_url(self) -> str | None:
        """
        Parses the tunnel.log file generated by cloudflared to extract the Quick Tunnel URL.
        Example log line:
        2023-10-10T12:00:00Z INF +--------------------------------------------------------------------------------------------+
        2023-10-10T12:00:00Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
        2023-10-10T12:00:00Z INF |  https://abc-123.trycloudflare.com                                                         |
        2023-10-10T12:00:00Z INF +--------------------------------------------------------------------------------------------+
        """
        if not self.log_file_path.exists():
            return None

        try:
            with open(self.log_file_path, "r", encoding="utf-8") as f:
                lines = f.readlines()
                
            # Scan backwards because the latest URL is at the bottom
            for line in reversed(lines):
                # Look for the trycloudflare.com domain pattern
                match = re.search(r'(https://[a-zA-Z0-9-]+\.trycloudflare\.com)', line)
                if match:
                    return match.group(1)
        except Exception:
            pass
            
        return None
